// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFKUNAG0ZywND3DVTuzWZG0UJ_UhlRY3w',
    appId: '1:196840839148:web:534638c673b7c9f1c512c9',
    messagingSenderId: '196840839148',
    projectId: 'jaltejas-b19a6',
    authDomain: 'jaltejas-b19a6.firebaseapp.com',
    databaseURL: 'https://jaltejas-b19a6-default-rtdb.firebaseio.com',
    storageBucket: 'jaltejas-b19a6.firebasestorage.app',
    measurementId: 'G-9L4R3QMTGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXiyJ0lMwDG_b5yKrdLoO7zvFZcrDH-fQ',
    appId: '1:196840839148:android:848a72e347bf8bffc512c9',
    messagingSenderId: '196840839148',
    projectId: 'jaltejas-b19a6',
    databaseURL: 'https://jaltejas-b19a6-default-rtdb.firebaseio.com',
    storageBucket: 'jaltejas-b19a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04bu4vD8slj75yPBPwcCHrIqO8lCyorU',
    appId: '1:196840839148:ios:e120d6ad20b894a5c512c9',
    messagingSenderId: '196840839148',
    projectId: 'jaltejas-b19a6',
    databaseURL: 'https://jaltejas-b19a6-default-rtdb.firebaseio.com',
    storageBucket: 'jaltejas-b19a6.firebasestorage.app',
    iosClientId: '196840839148-3j3gimk9irqbs3btlladu7fs9668vu53.apps.googleusercontent.com',
    iosBundleId: 'com.example.rovController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04bu4vD8slj75yPBPwcCHrIqO8lCyorU',
    appId: '1:196840839148:ios:e120d6ad20b894a5c512c9',
    messagingSenderId: '196840839148',
    projectId: 'jaltejas-b19a6',
    databaseURL: 'https://jaltejas-b19a6-default-rtdb.firebaseio.com',
    storageBucket: 'jaltejas-b19a6.firebasestorage.app',
    iosClientId: '196840839148-3j3gimk9irqbs3btlladu7fs9668vu53.apps.googleusercontent.com',
    iosBundleId: 'com.example.rovController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFKUNAG0ZywND3DVTuzWZG0UJ_UhlRY3w',
    appId: '1:196840839148:web:a17cf2b7e11fd1a4c512c9',
    messagingSenderId: '196840839148',
    projectId: 'jaltejas-b19a6',
    authDomain: 'jaltejas-b19a6.firebaseapp.com',
    databaseURL: 'https://jaltejas-b19a6-default-rtdb.firebaseio.com',
    storageBucket: 'jaltejas-b19a6.firebasestorage.app',
    measurementId: 'G-D4EF8V97HQ',
  );

}